// Code generated by go-swagger; DO NOT EDIT.

package resources

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// AddResourceCreatedCode is the HTTP code returned for type AddResourceCreated
const AddResourceCreatedCode int = 201

/*
AddResourceCreated Created

swagger:response addResourceCreated
*/
type AddResourceCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ResourceOut `json:"body,omitempty"`
}

// NewAddResourceCreated creates AddResourceCreated with default headers values
func NewAddResourceCreated() *AddResourceCreated {

	return &AddResourceCreated{}
}

// WithPayload adds the payload to the add resource created response
func (o *AddResourceCreated) WithPayload(payload *models.ResourceOut) *AddResourceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resource created response
func (o *AddResourceCreated) SetPayload(payload *models.ResourceOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResourceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddResourceBadRequestCode is the HTTP code returned for type AddResourceBadRequest
const AddResourceBadRequestCode int = 400

/*
AddResourceBadRequest Bad Request

swagger:response addResourceBadRequest
*/
type AddResourceBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewAddResourceBadRequest creates AddResourceBadRequest with default headers values
func NewAddResourceBadRequest() *AddResourceBadRequest {

	return &AddResourceBadRequest{}
}

// WithPayload adds the payload to the add resource bad request response
func (o *AddResourceBadRequest) WithPayload(payload *models.ErrorOut) *AddResourceBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resource bad request response
func (o *AddResourceBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResourceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddResourceInternalServerErrorCode is the HTTP code returned for type AddResourceInternalServerError
const AddResourceInternalServerErrorCode int = 500

/*
AddResourceInternalServerError Internal Server Error

swagger:response addResourceInternalServerError
*/
type AddResourceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewAddResourceInternalServerError creates AddResourceInternalServerError with default headers values
func NewAddResourceInternalServerError() *AddResourceInternalServerError {

	return &AddResourceInternalServerError{}
}

// WithPayload adds the payload to the add resource internal server error response
func (o *AddResourceInternalServerError) WithPayload(payload *models.ErrorOut) *AddResourceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resource internal server error response
func (o *AddResourceInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResourceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
