// Code generated by go-swagger; DO NOT EDIT.

package resources

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// DeleteResourceOKCode is the HTTP code returned for type DeleteResourceOK
const DeleteResourceOKCode int = 200

/*
DeleteResourceOK OK

swagger:response deleteResourceOK
*/
type DeleteResourceOK struct {
}

// NewDeleteResourceOK creates DeleteResourceOK with default headers values
func NewDeleteResourceOK() *DeleteResourceOK {

	return &DeleteResourceOK{}
}

// WriteResponse to the client
func (o *DeleteResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteResourceNotFoundCode is the HTTP code returned for type DeleteResourceNotFound
const DeleteResourceNotFoundCode int = 404

/*
DeleteResourceNotFound Not Found

swagger:response deleteResourceNotFound
*/
type DeleteResourceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceNotFound creates DeleteResourceNotFound with default headers values
func NewDeleteResourceNotFound() *DeleteResourceNotFound {

	return &DeleteResourceNotFound{}
}

// WithPayload adds the payload to the delete resource not found response
func (o *DeleteResourceNotFound) WithPayload(payload *models.ErrorOut) *DeleteResourceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource not found response
func (o *DeleteResourceNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourceInternalServerErrorCode is the HTTP code returned for type DeleteResourceInternalServerError
const DeleteResourceInternalServerErrorCode int = 500

/*
DeleteResourceInternalServerError Internal Server Error

swagger:response deleteResourceInternalServerError
*/
type DeleteResourceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceInternalServerError creates DeleteResourceInternalServerError with default headers values
func NewDeleteResourceInternalServerError() *DeleteResourceInternalServerError {

	return &DeleteResourceInternalServerError{}
}

// WithPayload adds the payload to the delete resource internal server error response
func (o *DeleteResourceInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteResourceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource internal server error response
func (o *DeleteResourceInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
