// Code generated by go-swagger; DO NOT EDIT.

package resources

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// DeleteResourceByNameURL generates an URL for the delete resource by name operation
type DeleteResourceByNameURL struct {
	ResourceName     string
	ResourceTypeName string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteResourceByNameURL) WithBasePath(bp string) *DeleteResourceByNameURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteResourceByNameURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteResourceByNameURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/resources"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	resourceNameQ := o.ResourceName
	if resourceNameQ != "" {
		qs.Set("resource_name", resourceNameQ)
	}

	resourceTypeNameQ := o.ResourceTypeName
	if resourceTypeNameQ != "" {
		qs.Set("resource_type_name", resourceTypeNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteResourceByNameURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteResourceByNameURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteResourceByNameURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteResourceByNameURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteResourceByNameURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteResourceByNameURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
