// Code generated by go-swagger; DO NOT EDIT.

package resources

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewDeleteResourceByNameParams creates a new DeleteResourceByNameParams object
//
// There are no default values defined in the spec.
func NewDeleteResourceByNameParams() DeleteResourceByNameParams {

	return DeleteResourceByNameParams{}
}

// DeleteResourceByNameParams contains all the bound params for the delete resource by name operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteResourceByName
type DeleteResourceByNameParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The resource name to search for.
	  Required: true
	  In: query
	*/
	ResourceName string

	/*The resource type name to search for.
	  Required: true
	  In: query
	*/
	ResourceTypeName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteResourceByNameParams() beforehand.
func (o *DeleteResourceByNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qResourceName, qhkResourceName, _ := qs.GetOK("resource_name")
	if err := o.bindResourceName(qResourceName, qhkResourceName, route.Formats); err != nil {
		res = append(res, err)
	}

	qResourceTypeName, qhkResourceTypeName, _ := qs.GetOK("resource_type_name")
	if err := o.bindResourceTypeName(qResourceTypeName, qhkResourceTypeName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindResourceName binds and validates parameter ResourceName from query.
func (o *DeleteResourceByNameParams) bindResourceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("resource_name", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("resource_name", "query", raw); err != nil {
		return err
	}
	o.ResourceName = raw

	return nil
}

// bindResourceTypeName binds and validates parameter ResourceTypeName from query.
func (o *DeleteResourceByNameParams) bindResourceTypeName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("resource_type_name", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("resource_type_name", "query", raw); err != nil {
		return err
	}
	o.ResourceTypeName = raw

	return nil
}
