// Code generated by go-swagger; DO NOT EDIT.

package resources

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// DeleteResourceByNameOKCode is the HTTP code returned for type DeleteResourceByNameOK
const DeleteResourceByNameOKCode int = 200

/*
DeleteResourceByNameOK OK

swagger:response deleteResourceByNameOK
*/
type DeleteResourceByNameOK struct {
}

// NewDeleteResourceByNameOK creates DeleteResourceByNameOK with default headers values
func NewDeleteResourceByNameOK() *DeleteResourceByNameOK {

	return &DeleteResourceByNameOK{}
}

// WriteResponse to the client
func (o *DeleteResourceByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteResourceByNameNotFoundCode is the HTTP code returned for type DeleteResourceByNameNotFound
const DeleteResourceByNameNotFoundCode int = 404

/*
DeleteResourceByNameNotFound Not Found

swagger:response deleteResourceByNameNotFound
*/
type DeleteResourceByNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceByNameNotFound creates DeleteResourceByNameNotFound with default headers values
func NewDeleteResourceByNameNotFound() *DeleteResourceByNameNotFound {

	return &DeleteResourceByNameNotFound{}
}

// WithPayload adds the payload to the delete resource by name not found response
func (o *DeleteResourceByNameNotFound) WithPayload(payload *models.ErrorOut) *DeleteResourceByNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource by name not found response
func (o *DeleteResourceByNameNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourceByNameInternalServerErrorCode is the HTTP code returned for type DeleteResourceByNameInternalServerError
const DeleteResourceByNameInternalServerErrorCode int = 500

/*
DeleteResourceByNameInternalServerError Internal Server Error

swagger:response deleteResourceByNameInternalServerError
*/
type DeleteResourceByNameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceByNameInternalServerError creates DeleteResourceByNameInternalServerError with default headers values
func NewDeleteResourceByNameInternalServerError() *DeleteResourceByNameInternalServerError {

	return &DeleteResourceByNameInternalServerError{}
}

// WithPayload adds the payload to the delete resource by name internal server error response
func (o *DeleteResourceByNameInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteResourceByNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource by name internal server error response
func (o *DeleteResourceByNameInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
