// Code generated by go-swagger; DO NOT EDIT.

package resources

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// ListResourcesOKCode is the HTTP code returned for type ListResourcesOK
const ListResourcesOKCode int = 200

/*
ListResourcesOK OK

swagger:response listResourcesOK
*/
type ListResourcesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResourcesOut `json:"body,omitempty"`
}

// NewListResourcesOK creates ListResourcesOK with default headers values
func NewListResourcesOK() *ListResourcesOK {

	return &ListResourcesOK{}
}

// WithPayload adds the payload to the list resources o k response
func (o *ListResourcesOK) WithPayload(payload *models.ResourcesOut) *ListResourcesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resources o k response
func (o *ListResourcesOK) SetPayload(payload *models.ResourcesOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourcesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListResourcesInternalServerErrorCode is the HTTP code returned for type ListResourcesInternalServerError
const ListResourcesInternalServerErrorCode int = 500

/*
ListResourcesInternalServerError Internal Server Error

swagger:response listResourcesInternalServerError
*/
type ListResourcesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewListResourcesInternalServerError creates ListResourcesInternalServerError with default headers values
func NewListResourcesInternalServerError() *ListResourcesInternalServerError {

	return &ListResourcesInternalServerError{}
}

// WithPayload adds the payload to the list resources internal server error response
func (o *ListResourcesInternalServerError) WithPayload(payload *models.ErrorOut) *ListResourcesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resources internal server error response
func (o *ListResourcesInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourcesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
