// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// BySubjectURL generates an URL for the by subject operation
type BySubjectURL struct {
	SubjectID   string
	SubjectType string

	Lookup   *bool
	MinLevel *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *BySubjectURL) WithBasePath(bp string) *BySubjectURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *BySubjectURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *BySubjectURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/permissions/subjects/{subject_type}/{subject_id}"

	subjectID := o.SubjectID
	if subjectID != "" {
		_path = strings.ReplaceAll(_path, "{subject_id}", subjectID)
	} else {
		return nil, errors.New("subjectId is required on BySubjectURL")
	}

	subjectType := o.SubjectType
	if subjectType != "" {
		_path = strings.ReplaceAll(_path, "{subject_type}", subjectType)
	} else {
		return nil, errors.New("subjectType is required on BySubjectURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var lookupQ string
	if o.Lookup != nil {
		lookupQ = swag.FormatBool(*o.Lookup)
	}
	if lookupQ != "" {
		qs.Set("lookup", lookupQ)
	}

	var minLevelQ string
	if o.MinLevel != nil {
		minLevelQ = *o.MinLevel
	}
	if minLevelQ != "" {
		qs.Set("min_level", minLevelQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *BySubjectURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *BySubjectURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *BySubjectURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on BySubjectURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on BySubjectURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *BySubjectURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
