// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	stderrors "errors"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/cyverse-de/permissions/models"
)

// NewCopyPermissionsParams creates a new CopyPermissionsParams object
//
// There are no default values defined in the spec.
func NewCopyPermissionsParams() CopyPermissionsParams {

	return CopyPermissionsParams{}
}

// CopyPermissionsParams contains all the bound params for the copy permissions operation
// typically these are obtained from a http.Request
//
// swagger:parameters copyPermissions
type CopyPermissionsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The destination subjects.
	  Required: true
	  In: body
	*/
	DestSubjects *models.SubjectsIn

	/*The external subject identifier.
	  Required: true
	  In: path
	*/
	SubjectID string

	/*The subject type name.
	  Required: true
	  In: path
	*/
	SubjectType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCopyPermissionsParams() beforehand.
func (o *CopyPermissionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer func() {
			_ = r.Body.Close()
		}()
		var body models.SubjectsIn
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if stderrors.Is(err, io.EOF) {
				res = append(res, errors.Required("destSubjects", "body", ""))
			} else {
				res = append(res, errors.NewParseError("destSubjects", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.DestSubjects = &body
			}
		}
	} else {
		res = append(res, errors.Required("destSubjects", "body", ""))
	}

	rSubjectID, rhkSubjectID, _ := route.Params.GetOK("subject_id")
	if err := o.bindSubjectID(rSubjectID, rhkSubjectID, route.Formats); err != nil {
		res = append(res, err)
	}

	rSubjectType, rhkSubjectType, _ := route.Params.GetOK("subject_type")
	if err := o.bindSubjectType(rSubjectType, rhkSubjectType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSubjectID binds and validates parameter SubjectID from path.
func (o *CopyPermissionsParams) bindSubjectID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SubjectID = raw

	return nil
}

// bindSubjectType binds and validates parameter SubjectType from path.
func (o *CopyPermissionsParams) bindSubjectType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SubjectType = raw

	if err := o.validateSubjectType(formats); err != nil {
		return err
	}

	return nil
}

// validateSubjectType carries out validations for parameter SubjectType
func (o *CopyPermissionsParams) validateSubjectType(formats strfmt.Registry) error {

	if err := validate.EnumCase("subject_type", "path", o.SubjectType, []any{"user", "group"}, true); err != nil {
		return err
	}

	return nil
}
