// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// CopyPermissionsOKCode is the HTTP code returned for type CopyPermissionsOK
const CopyPermissionsOKCode int = 200

/*
CopyPermissionsOK OK

swagger:response copyPermissionsOK
*/
type CopyPermissionsOK struct {
}

// NewCopyPermissionsOK creates CopyPermissionsOK with default headers values
func NewCopyPermissionsOK() *CopyPermissionsOK {

	return &CopyPermissionsOK{}
}

// WriteResponse to the client
func (o *CopyPermissionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CopyPermissionsBadRequestCode is the HTTP code returned for type CopyPermissionsBadRequest
const CopyPermissionsBadRequestCode int = 400

/*
CopyPermissionsBadRequest Bad Request

swagger:response copyPermissionsBadRequest
*/
type CopyPermissionsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewCopyPermissionsBadRequest creates CopyPermissionsBadRequest with default headers values
func NewCopyPermissionsBadRequest() *CopyPermissionsBadRequest {

	return &CopyPermissionsBadRequest{}
}

// WithPayload adds the payload to the copy permissions bad request response
func (o *CopyPermissionsBadRequest) WithPayload(payload *models.ErrorOut) *CopyPermissionsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the copy permissions bad request response
func (o *CopyPermissionsBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CopyPermissionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CopyPermissionsInternalServerErrorCode is the HTTP code returned for type CopyPermissionsInternalServerError
const CopyPermissionsInternalServerErrorCode int = 500

/*
CopyPermissionsInternalServerError Internal Server Error

swagger:response copyPermissionsInternalServerError
*/
type CopyPermissionsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewCopyPermissionsInternalServerError creates CopyPermissionsInternalServerError with default headers values
func NewCopyPermissionsInternalServerError() *CopyPermissionsInternalServerError {

	return &CopyPermissionsInternalServerError{}
}

// WithPayload adds the payload to the copy permissions internal server error response
func (o *CopyPermissionsInternalServerError) WithPayload(payload *models.ErrorOut) *CopyPermissionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the copy permissions internal server error response
func (o *CopyPermissionsInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CopyPermissionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
