// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// ListResourcePermissionsOKCode is the HTTP code returned for type ListResourcePermissionsOK
const ListResourcePermissionsOKCode int = 200

/*
ListResourcePermissionsOK OK

swagger:response listResourcePermissionsOK
*/
type ListResourcePermissionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PermissionList `json:"body,omitempty"`
}

// NewListResourcePermissionsOK creates ListResourcePermissionsOK with default headers values
func NewListResourcePermissionsOK() *ListResourcePermissionsOK {

	return &ListResourcePermissionsOK{}
}

// WithPayload adds the payload to the list resource permissions o k response
func (o *ListResourcePermissionsOK) WithPayload(payload *models.PermissionList) *ListResourcePermissionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource permissions o k response
func (o *ListResourcePermissionsOK) SetPayload(payload *models.PermissionList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourcePermissionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListResourcePermissionsInternalServerErrorCode is the HTTP code returned for type ListResourcePermissionsInternalServerError
const ListResourcePermissionsInternalServerErrorCode int = 500

/*
ListResourcePermissionsInternalServerError Internal Server Error

swagger:response listResourcePermissionsInternalServerError
*/
type ListResourcePermissionsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewListResourcePermissionsInternalServerError creates ListResourcePermissionsInternalServerError with default headers values
func NewListResourcePermissionsInternalServerError() *ListResourcePermissionsInternalServerError {

	return &ListResourcePermissionsInternalServerError{}
}

// WithPayload adds the payload to the list resource permissions internal server error response
func (o *ListResourcePermissionsInternalServerError) WithPayload(payload *models.ErrorOut) *ListResourcePermissionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource permissions internal server error response
func (o *ListResourcePermissionsInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourcePermissionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
