// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListPermissionsParams creates a new ListPermissionsParams object
//
// There are no default values defined in the spec.
func NewListPermissionsParams() ListPermissionsParams {

	return ListPermissionsParams{}
}

// ListPermissionsParams contains all the bound params for the list permissions operation
// typically these are obtained from a http.Request
//
// swagger:parameters listPermissions
type ListPermissionsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListPermissionsParams() beforehand.
func (o *ListPermissionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
