// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListResourcePermissionsParams creates a new ListResourcePermissionsParams object
// with the default values initialized.
func NewListResourcePermissionsParams() ListResourcePermissionsParams {

	var (
		// initialize parameters with default values

		expandGroupsDefault = bool(false)
	)

	return ListResourcePermissionsParams{
		ExpandGroups: &expandGroupsDefault,
	}
}

// ListResourcePermissionsParams contains all the bound params for the list resource permissions operation
// typically these are obtained from a http.Request
//
// swagger:parameters listResourcePermissions
type ListResourcePermissionsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Expand groups to lists of group members if true. Defaults to false.
	  In: query
	  Default: false
	*/
	ExpandGroups *bool

	/*The resource name.
	  Required: true
	  In: path
	*/
	ResourceName string

	/*The resource type name.
	  Required: true
	  In: path
	*/
	ResourceType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListResourcePermissionsParams() beforehand.
func (o *ListResourcePermissionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qExpandGroups, qhkExpandGroups, _ := qs.GetOK("expand_groups")
	if err := o.bindExpandGroups(qExpandGroups, qhkExpandGroups, route.Formats); err != nil {
		res = append(res, err)
	}

	rResourceName, rhkResourceName, _ := route.Params.GetOK("resource_name")
	if err := o.bindResourceName(rResourceName, rhkResourceName, route.Formats); err != nil {
		res = append(res, err)
	}

	rResourceType, rhkResourceType, _ := route.Params.GetOK("resource_type")
	if err := o.bindResourceType(rResourceType, rhkResourceType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindExpandGroups binds and validates parameter ExpandGroups from query.
func (o *ListResourcePermissionsParams) bindExpandGroups(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewListResourcePermissionsParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("expand_groups", "query", "bool", raw)
	}
	o.ExpandGroups = &value

	return nil
}

// bindResourceName binds and validates parameter ResourceName from path.
func (o *ListResourcePermissionsParams) bindResourceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ResourceName = raw

	return nil
}

// bindResourceType binds and validates parameter ResourceType from path.
func (o *ListResourcePermissionsParams) bindResourceType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ResourceType = raw

	return nil
}
