// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// ListResourcePermissionsURL generates an URL for the list resource permissions operation
type ListResourcePermissionsURL struct {
	ResourceName string
	ResourceType string

	ExpandGroups *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListResourcePermissionsURL) WithBasePath(bp string) *ListResourcePermissionsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListResourcePermissionsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ListResourcePermissionsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/permissions/resources/{resource_type}/{resource_name}"

	resourceName := o.ResourceName
	if resourceName != "" {
		_path = strings.ReplaceAll(_path, "{resource_name}", resourceName)
	} else {
		return nil, errors.New("resourceName is required on ListResourcePermissionsURL")
	}

	resourceType := o.ResourceType
	if resourceType != "" {
		_path = strings.ReplaceAll(_path, "{resource_type}", resourceType)
	} else {
		return nil, errors.New("resourceType is required on ListResourcePermissionsURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var expandGroupsQ string
	if o.ExpandGroups != nil {
		expandGroupsQ = swag.FormatBool(*o.ExpandGroups)
	}
	if expandGroupsQ != "" {
		qs.Set("expand_groups", expandGroupsQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ListResourcePermissionsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ListResourcePermissionsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ListResourcePermissionsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ListResourcePermissionsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ListResourcePermissionsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ListResourcePermissionsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
