// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// PutPermissionURL generates an URL for the put permission operation
type PutPermissionURL struct {
	ResourceName string
	ResourceType string
	SubjectID    string
	SubjectType  string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutPermissionURL) WithBasePath(bp string) *PutPermissionURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutPermissionURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PutPermissionURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/permissions/resources/{resource_type}/{resource_name}/subjects/{subject_type}/{subject_id}"

	resourceName := o.ResourceName
	if resourceName != "" {
		_path = strings.ReplaceAll(_path, "{resource_name}", resourceName)
	} else {
		return nil, errors.New("resourceName is required on PutPermissionURL")
	}

	resourceType := o.ResourceType
	if resourceType != "" {
		_path = strings.ReplaceAll(_path, "{resource_type}", resourceType)
	} else {
		return nil, errors.New("resourceType is required on PutPermissionURL")
	}

	subjectID := o.SubjectID
	if subjectID != "" {
		_path = strings.ReplaceAll(_path, "{subject_id}", subjectID)
	} else {
		return nil, errors.New("subjectId is required on PutPermissionURL")
	}

	subjectType := o.SubjectType
	if subjectType != "" {
		_path = strings.ReplaceAll(_path, "{subject_type}", subjectType)
	} else {
		return nil, errors.New("subjectType is required on PutPermissionURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PutPermissionURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PutPermissionURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PutPermissionURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PutPermissionURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PutPermissionURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PutPermissionURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
