// Code generated by go-swagger; DO NOT EDIT.

package permissions

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// RevokePermissionOKCode is the HTTP code returned for type RevokePermissionOK
const RevokePermissionOKCode int = 200

/*
RevokePermissionOK OK

swagger:response revokePermissionOK
*/
type RevokePermissionOK struct {
}

// NewRevokePermissionOK creates RevokePermissionOK with default headers values
func NewRevokePermissionOK() *RevokePermissionOK {

	return &RevokePermissionOK{}
}

// WriteResponse to the client
func (o *RevokePermissionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RevokePermissionNotFoundCode is the HTTP code returned for type RevokePermissionNotFound
const RevokePermissionNotFoundCode int = 404

/*
RevokePermissionNotFound Not Found

swagger:response revokePermissionNotFound
*/
type RevokePermissionNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewRevokePermissionNotFound creates RevokePermissionNotFound with default headers values
func NewRevokePermissionNotFound() *RevokePermissionNotFound {

	return &RevokePermissionNotFound{}
}

// WithPayload adds the payload to the revoke permission not found response
func (o *RevokePermissionNotFound) WithPayload(payload *models.ErrorOut) *RevokePermissionNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the revoke permission not found response
func (o *RevokePermissionNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RevokePermissionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RevokePermissionInternalServerErrorCode is the HTTP code returned for type RevokePermissionInternalServerError
const RevokePermissionInternalServerErrorCode int = 500

/*
RevokePermissionInternalServerError Internal Server Error

swagger:response revokePermissionInternalServerError
*/
type RevokePermissionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewRevokePermissionInternalServerError creates RevokePermissionInternalServerError with default headers values
func NewRevokePermissionInternalServerError() *RevokePermissionInternalServerError {

	return &RevokePermissionInternalServerError{}
}

// WithPayload adds the payload to the revoke permission internal server error response
func (o *RevokePermissionInternalServerError) WithPayload(payload *models.ErrorOut) *RevokePermissionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the revoke permission internal server error response
func (o *RevokePermissionInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RevokePermissionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
