// Code generated by go-swagger; DO NOT EDIT.

package resource_types

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// DeleteResourceTypeByNameOKCode is the HTTP code returned for type DeleteResourceTypeByNameOK
const DeleteResourceTypeByNameOKCode int = 200

/*
DeleteResourceTypeByNameOK Deleted

swagger:response deleteResourceTypeByNameOK
*/
type DeleteResourceTypeByNameOK struct {
}

// NewDeleteResourceTypeByNameOK creates DeleteResourceTypeByNameOK with default headers values
func NewDeleteResourceTypeByNameOK() *DeleteResourceTypeByNameOK {

	return &DeleteResourceTypeByNameOK{}
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteResourceTypeByNameBadRequestCode is the HTTP code returned for type DeleteResourceTypeByNameBadRequest
const DeleteResourceTypeByNameBadRequestCode int = 400

/*
DeleteResourceTypeByNameBadRequest Bad Request

swagger:response deleteResourceTypeByNameBadRequest
*/
type DeleteResourceTypeByNameBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceTypeByNameBadRequest creates DeleteResourceTypeByNameBadRequest with default headers values
func NewDeleteResourceTypeByNameBadRequest() *DeleteResourceTypeByNameBadRequest {

	return &DeleteResourceTypeByNameBadRequest{}
}

// WithPayload adds the payload to the delete resource type by name bad request response
func (o *DeleteResourceTypeByNameBadRequest) WithPayload(payload *models.ErrorOut) *DeleteResourceTypeByNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource type by name bad request response
func (o *DeleteResourceTypeByNameBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourceTypeByNameNotFoundCode is the HTTP code returned for type DeleteResourceTypeByNameNotFound
const DeleteResourceTypeByNameNotFoundCode int = 404

/*
DeleteResourceTypeByNameNotFound Not Found

swagger:response deleteResourceTypeByNameNotFound
*/
type DeleteResourceTypeByNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceTypeByNameNotFound creates DeleteResourceTypeByNameNotFound with default headers values
func NewDeleteResourceTypeByNameNotFound() *DeleteResourceTypeByNameNotFound {

	return &DeleteResourceTypeByNameNotFound{}
}

// WithPayload adds the payload to the delete resource type by name not found response
func (o *DeleteResourceTypeByNameNotFound) WithPayload(payload *models.ErrorOut) *DeleteResourceTypeByNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource type by name not found response
func (o *DeleteResourceTypeByNameNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourceTypeByNameInternalServerErrorCode is the HTTP code returned for type DeleteResourceTypeByNameInternalServerError
const DeleteResourceTypeByNameInternalServerErrorCode int = 500

/*
DeleteResourceTypeByNameInternalServerError Internal Server Error

swagger:response deleteResourceTypeByNameInternalServerError
*/
type DeleteResourceTypeByNameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceTypeByNameInternalServerError creates DeleteResourceTypeByNameInternalServerError with default headers values
func NewDeleteResourceTypeByNameInternalServerError() *DeleteResourceTypeByNameInternalServerError {

	return &DeleteResourceTypeByNameInternalServerError{}
}

// WithPayload adds the payload to the delete resource type by name internal server error response
func (o *DeleteResourceTypeByNameInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteResourceTypeByNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource type by name internal server error response
func (o *DeleteResourceTypeByNameInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
