// Code generated by go-swagger; DO NOT EDIT.

package resource_types

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// GetResourceTypesOKCode is the HTTP code returned for type GetResourceTypesOK
const GetResourceTypesOKCode int = 200

/*
GetResourceTypesOK Success

swagger:response getResourceTypesOK
*/
type GetResourceTypesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResourceTypesOut `json:"body,omitempty"`
}

// NewGetResourceTypesOK creates GetResourceTypesOK with default headers values
func NewGetResourceTypesOK() *GetResourceTypesOK {

	return &GetResourceTypesOK{}
}

// WithPayload adds the payload to the get resource types o k response
func (o *GetResourceTypesOK) WithPayload(payload *models.ResourceTypesOut) *GetResourceTypesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resource types o k response
func (o *GetResourceTypesOK) SetPayload(payload *models.ResourceTypesOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourceTypesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourceTypesInternalServerErrorCode is the HTTP code returned for type GetResourceTypesInternalServerError
const GetResourceTypesInternalServerErrorCode int = 500

/*
GetResourceTypesInternalServerError Internal Server Error

swagger:response getResourceTypesInternalServerError
*/
type GetResourceTypesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewGetResourceTypesInternalServerError creates GetResourceTypesInternalServerError with default headers values
func NewGetResourceTypesInternalServerError() *GetResourceTypesInternalServerError {

	return &GetResourceTypesInternalServerError{}
}

// WithPayload adds the payload to the get resource types internal server error response
func (o *GetResourceTypesInternalServerError) WithPayload(payload *models.ErrorOut) *GetResourceTypesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resource types internal server error response
func (o *GetResourceTypesInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourceTypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
