// Code generated by go-swagger; DO NOT EDIT.

package resource_types

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// PostResourceTypesCreatedCode is the HTTP code returned for type PostResourceTypesCreated
const PostResourceTypesCreatedCode int = 201

/*
PostResourceTypesCreated Created

swagger:response postResourceTypesCreated
*/
type PostResourceTypesCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ResourceTypeOut `json:"body,omitempty"`
}

// NewPostResourceTypesCreated creates PostResourceTypesCreated with default headers values
func NewPostResourceTypesCreated() *PostResourceTypesCreated {

	return &PostResourceTypesCreated{}
}

// WithPayload adds the payload to the post resource types created response
func (o *PostResourceTypesCreated) WithPayload(payload *models.ResourceTypeOut) *PostResourceTypesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource types created response
func (o *PostResourceTypesCreated) SetPayload(payload *models.ResourceTypeOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceTypesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResourceTypesBadRequestCode is the HTTP code returned for type PostResourceTypesBadRequest
const PostResourceTypesBadRequestCode int = 400

/*
PostResourceTypesBadRequest Bad Request

swagger:response postResourceTypesBadRequest
*/
type PostResourceTypesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewPostResourceTypesBadRequest creates PostResourceTypesBadRequest with default headers values
func NewPostResourceTypesBadRequest() *PostResourceTypesBadRequest {

	return &PostResourceTypesBadRequest{}
}

// WithPayload adds the payload to the post resource types bad request response
func (o *PostResourceTypesBadRequest) WithPayload(payload *models.ErrorOut) *PostResourceTypesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource types bad request response
func (o *PostResourceTypesBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceTypesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResourceTypesInternalServerErrorCode is the HTTP code returned for type PostResourceTypesInternalServerError
const PostResourceTypesInternalServerErrorCode int = 500

/*
PostResourceTypesInternalServerError Internal Server Error

swagger:response postResourceTypesInternalServerError
*/
type PostResourceTypesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewPostResourceTypesInternalServerError creates PostResourceTypesInternalServerError with default headers values
func NewPostResourceTypesInternalServerError() *PostResourceTypesInternalServerError {

	return &PostResourceTypesInternalServerError{}
}

// WithPayload adds the payload to the post resource types internal server error response
func (o *PostResourceTypesInternalServerError) WithPayload(payload *models.ErrorOut) *PostResourceTypesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource types internal server error response
func (o *PostResourceTypesInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceTypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
