// Code generated by go-swagger; DO NOT EDIT.

package resource_types

import (
	stderrors "errors"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/cyverse-de/permissions/models"
)

// NewPutResourceTypesIDParams creates a new PutResourceTypesIDParams object
//
// There are no default values defined in the spec.
func NewPutResourceTypesIDParams() PutResourceTypesIDParams {

	return PutResourceTypesIDParams{}
}

// PutResourceTypesIDParams contains all the bound params for the put resource types ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutResourceTypesID
type PutResourceTypesIDParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The resource type ID.
	  Required: true
	  In: path
	*/
	ID string

	/*The new name and description of the resource type.
	  Required: true
	  In: body
	*/
	ResourceTypeIn *models.ResourceTypeIn
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutResourceTypesIDParams() beforehand.
func (o *PutResourceTypesIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer func() {
			_ = r.Body.Close()
		}()
		var body models.ResourceTypeIn
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if stderrors.Is(err, io.EOF) {
				res = append(res, errors.Required("resourceTypeIn", "body", ""))
			} else {
				res = append(res, errors.NewParseError("resourceTypeIn", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ResourceTypeIn = &body
			}
		}
	} else {
		res = append(res, errors.Required("resourceTypeIn", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *PutResourceTypesIDParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ID = raw

	return nil
}
