// Code generated by go-swagger; DO NOT EDIT.

package resource_types

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// PutResourceTypesIDURL generates an URL for the put resource types ID operation
type PutResourceTypesIDURL struct {
	ID string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutResourceTypesIDURL) WithBasePath(bp string) *PutResourceTypesIDURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutResourceTypesIDURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PutResourceTypesIDURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/resource_types/{id}"

	id := o.ID
	if id != "" {
		_path = strings.ReplaceAll(_path, "{id}", id)
	} else {
		return nil, errors.New("id is required on PutResourceTypesIDURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PutResourceTypesIDURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PutResourceTypesIDURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PutResourceTypesIDURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PutResourceTypesIDURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PutResourceTypesIDURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PutResourceTypesIDURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
