// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// AddSubjectCreatedCode is the HTTP code returned for type AddSubjectCreated
const AddSubjectCreatedCode int = 201

/*
AddSubjectCreated Created

swagger:response addSubjectCreated
*/
type AddSubjectCreated struct {

	/*
	  In: Body
	*/
	Payload *models.SubjectOut `json:"body,omitempty"`
}

// NewAddSubjectCreated creates AddSubjectCreated with default headers values
func NewAddSubjectCreated() *AddSubjectCreated {

	return &AddSubjectCreated{}
}

// WithPayload adds the payload to the add subject created response
func (o *AddSubjectCreated) WithPayload(payload *models.SubjectOut) *AddSubjectCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add subject created response
func (o *AddSubjectCreated) SetPayload(payload *models.SubjectOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSubjectCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddSubjectBadRequestCode is the HTTP code returned for type AddSubjectBadRequest
const AddSubjectBadRequestCode int = 400

/*
AddSubjectBadRequest Bad Request

swagger:response addSubjectBadRequest
*/
type AddSubjectBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewAddSubjectBadRequest creates AddSubjectBadRequest with default headers values
func NewAddSubjectBadRequest() *AddSubjectBadRequest {

	return &AddSubjectBadRequest{}
}

// WithPayload adds the payload to the add subject bad request response
func (o *AddSubjectBadRequest) WithPayload(payload *models.ErrorOut) *AddSubjectBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add subject bad request response
func (o *AddSubjectBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSubjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddSubjectInternalServerErrorCode is the HTTP code returned for type AddSubjectInternalServerError
const AddSubjectInternalServerErrorCode int = 500

/*
AddSubjectInternalServerError Internal Server Error

swagger:response addSubjectInternalServerError
*/
type AddSubjectInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewAddSubjectInternalServerError creates AddSubjectInternalServerError with default headers values
func NewAddSubjectInternalServerError() *AddSubjectInternalServerError {

	return &AddSubjectInternalServerError{}
}

// WithPayload adds the payload to the add subject internal server error response
func (o *AddSubjectInternalServerError) WithPayload(payload *models.ErrorOut) *AddSubjectInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add subject internal server error response
func (o *AddSubjectInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSubjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
