// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// DeleteSubjectByExternalIDOKCode is the HTTP code returned for type DeleteSubjectByExternalIDOK
const DeleteSubjectByExternalIDOKCode int = 200

/*
DeleteSubjectByExternalIDOK OK

swagger:response deleteSubjectByExternalIdOK
*/
type DeleteSubjectByExternalIDOK struct {
}

// NewDeleteSubjectByExternalIDOK creates DeleteSubjectByExternalIDOK with default headers values
func NewDeleteSubjectByExternalIDOK() *DeleteSubjectByExternalIDOK {

	return &DeleteSubjectByExternalIDOK{}
}

// WriteResponse to the client
func (o *DeleteSubjectByExternalIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteSubjectByExternalIDNotFoundCode is the HTTP code returned for type DeleteSubjectByExternalIDNotFound
const DeleteSubjectByExternalIDNotFoundCode int = 404

/*
DeleteSubjectByExternalIDNotFound Not Found

swagger:response deleteSubjectByExternalIdNotFound
*/
type DeleteSubjectByExternalIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteSubjectByExternalIDNotFound creates DeleteSubjectByExternalIDNotFound with default headers values
func NewDeleteSubjectByExternalIDNotFound() *DeleteSubjectByExternalIDNotFound {

	return &DeleteSubjectByExternalIDNotFound{}
}

// WithPayload adds the payload to the delete subject by external Id not found response
func (o *DeleteSubjectByExternalIDNotFound) WithPayload(payload *models.ErrorOut) *DeleteSubjectByExternalIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete subject by external Id not found response
func (o *DeleteSubjectByExternalIDNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSubjectByExternalIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteSubjectByExternalIDInternalServerErrorCode is the HTTP code returned for type DeleteSubjectByExternalIDInternalServerError
const DeleteSubjectByExternalIDInternalServerErrorCode int = 500

/*
DeleteSubjectByExternalIDInternalServerError Internal Server Error

swagger:response deleteSubjectByExternalIdInternalServerError
*/
type DeleteSubjectByExternalIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteSubjectByExternalIDInternalServerError creates DeleteSubjectByExternalIDInternalServerError with default headers values
func NewDeleteSubjectByExternalIDInternalServerError() *DeleteSubjectByExternalIDInternalServerError {

	return &DeleteSubjectByExternalIDInternalServerError{}
}

// WithPayload adds the payload to the delete subject by external Id internal server error response
func (o *DeleteSubjectByExternalIDInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteSubjectByExternalIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete subject by external Id internal server error response
func (o *DeleteSubjectByExternalIDInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSubjectByExternalIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
