// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// DeleteSubjectOKCode is the HTTP code returned for type DeleteSubjectOK
const DeleteSubjectOKCode int = 200

/*
DeleteSubjectOK OK

swagger:response deleteSubjectOK
*/
type DeleteSubjectOK struct {
}

// NewDeleteSubjectOK creates DeleteSubjectOK with default headers values
func NewDeleteSubjectOK() *DeleteSubjectOK {

	return &DeleteSubjectOK{}
}

// WriteResponse to the client
func (o *DeleteSubjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteSubjectNotFoundCode is the HTTP code returned for type DeleteSubjectNotFound
const DeleteSubjectNotFoundCode int = 404

/*
DeleteSubjectNotFound Not Found

swagger:response deleteSubjectNotFound
*/
type DeleteSubjectNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteSubjectNotFound creates DeleteSubjectNotFound with default headers values
func NewDeleteSubjectNotFound() *DeleteSubjectNotFound {

	return &DeleteSubjectNotFound{}
}

// WithPayload adds the payload to the delete subject not found response
func (o *DeleteSubjectNotFound) WithPayload(payload *models.ErrorOut) *DeleteSubjectNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete subject not found response
func (o *DeleteSubjectNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSubjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteSubjectInternalServerErrorCode is the HTTP code returned for type DeleteSubjectInternalServerError
const DeleteSubjectInternalServerErrorCode int = 500

/*
DeleteSubjectInternalServerError Internal Server Error

swagger:response deleteSubjectInternalServerError
*/
type DeleteSubjectInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteSubjectInternalServerError creates DeleteSubjectInternalServerError with default headers values
func NewDeleteSubjectInternalServerError() *DeleteSubjectInternalServerError {

	return &DeleteSubjectInternalServerError{}
}

// WithPayload adds the payload to the delete subject internal server error response
func (o *DeleteSubjectInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteSubjectInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete subject internal server error response
func (o *DeleteSubjectInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSubjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
