// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// ListSubjectsURL generates an URL for the list subjects operation
type ListSubjectsURL struct {
	SubjectID   *string
	SubjectType *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListSubjectsURL) WithBasePath(bp string) *ListSubjectsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListSubjectsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ListSubjectsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/subjects"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var subjectIDQ string
	if o.SubjectID != nil {
		subjectIDQ = *o.SubjectID
	}
	if subjectIDQ != "" {
		qs.Set("subject_id", subjectIDQ)
	}

	var subjectTypeQ string
	if o.SubjectType != nil {
		subjectTypeQ = *o.SubjectType
	}
	if subjectTypeQ != "" {
		qs.Set("subject_type", subjectTypeQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ListSubjectsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ListSubjectsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ListSubjectsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ListSubjectsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ListSubjectsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ListSubjectsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
