// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListSubjectsHandlerFunc turns a function with the right signature into a list subjects handler
type ListSubjectsHandlerFunc func(ListSubjectsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListSubjectsHandlerFunc) Handle(params ListSubjectsParams) middleware.Responder {
	return fn(params)
}

// ListSubjectsHandler interface for that can handle valid list subjects params
type ListSubjectsHandler interface {
	Handle(ListSubjectsParams) middleware.Responder
}

// NewListSubjects creates a new http.Handler for the list subjects operation
func NewListSubjects(ctx *middleware.Context, handler ListSubjectsHandler) *ListSubjects {
	return &ListSubjects{Context: ctx, Handler: handler}
}

/*
	ListSubjects swagger:route GET /subjects subjects listSubjects

# List Subjects

Lists subjects (entities to which permissions may be gratned) that exist in the database.
*/
type ListSubjects struct {
	Context *middleware.Context
	Handler ListSubjectsHandler
}

func (o *ListSubjects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListSubjectsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
