// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewListSubjectsParams creates a new ListSubjectsParams object
//
// There are no default values defined in the spec.
func NewListSubjectsParams() ListSubjectsParams {

	return ListSubjectsParams{}
}

// ListSubjectsParams contains all the bound params for the list subjects operation
// typically these are obtained from a http.Request
//
// swagger:parameters listSubjects
type ListSubjectsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The external subject identifier.
	  In: query
	*/
	SubjectID *string

	/*The subject type.
	  In: query
	*/
	SubjectType *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListSubjectsParams() beforehand.
func (o *ListSubjectsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qSubjectID, qhkSubjectID, _ := qs.GetOK("subject_id")
	if err := o.bindSubjectID(qSubjectID, qhkSubjectID, route.Formats); err != nil {
		res = append(res, err)
	}

	qSubjectType, qhkSubjectType, _ := qs.GetOK("subject_type")
	if err := o.bindSubjectType(qSubjectType, qhkSubjectType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSubjectID binds and validates parameter SubjectID from query.
func (o *ListSubjectsParams) bindSubjectID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SubjectID = &raw

	return nil
}

// bindSubjectType binds and validates parameter SubjectType from query.
func (o *ListSubjectsParams) bindSubjectType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SubjectType = &raw

	if err := o.validateSubjectType(formats); err != nil {
		return err
	}

	return nil
}

// validateSubjectType carries out validations for parameter SubjectType
func (o *ListSubjectsParams) validateSubjectType(formats strfmt.Registry) error {

	if err := validate.EnumCase("subject_type", "query", *o.SubjectType, []any{"user", "group"}, true); err != nil {
		return err
	}

	return nil
}
