// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// ListSubjectsOKCode is the HTTP code returned for type ListSubjectsOK
const ListSubjectsOKCode int = 200

/*
ListSubjectsOK OK

swagger:response listSubjectsOK
*/
type ListSubjectsOK struct {

	/*
	  In: Body
	*/
	Payload *models.SubjectsOut `json:"body,omitempty"`
}

// NewListSubjectsOK creates ListSubjectsOK with default headers values
func NewListSubjectsOK() *ListSubjectsOK {

	return &ListSubjectsOK{}
}

// WithPayload adds the payload to the list subjects o k response
func (o *ListSubjectsOK) WithPayload(payload *models.SubjectsOut) *ListSubjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list subjects o k response
func (o *ListSubjectsOK) SetPayload(payload *models.SubjectsOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSubjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListSubjectsInternalServerErrorCode is the HTTP code returned for type ListSubjectsInternalServerError
const ListSubjectsInternalServerErrorCode int = 500

/*
ListSubjectsInternalServerError Internal Server Error

swagger:response listSubjectsInternalServerError
*/
type ListSubjectsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewListSubjectsInternalServerError creates ListSubjectsInternalServerError with default headers values
func NewListSubjectsInternalServerError() *ListSubjectsInternalServerError {

	return &ListSubjectsInternalServerError{}
}

// WithPayload adds the payload to the list subjects internal server error response
func (o *ListSubjectsInternalServerError) WithPayload(payload *models.ErrorOut) *ListSubjectsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list subjects internal server error response
func (o *ListSubjectsInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSubjectsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
