// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cyverse-de/permissions/models"
)

// UpdateSubjectOKCode is the HTTP code returned for type UpdateSubjectOK
const UpdateSubjectOKCode int = 200

/*
UpdateSubjectOK OK

swagger:response updateSubjectOK
*/
type UpdateSubjectOK struct {

	/*
	  In: Body
	*/
	Payload *models.SubjectOut `json:"body,omitempty"`
}

// NewUpdateSubjectOK creates UpdateSubjectOK with default headers values
func NewUpdateSubjectOK() *UpdateSubjectOK {

	return &UpdateSubjectOK{}
}

// WithPayload adds the payload to the update subject o k response
func (o *UpdateSubjectOK) WithPayload(payload *models.SubjectOut) *UpdateSubjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update subject o k response
func (o *UpdateSubjectOK) SetPayload(payload *models.SubjectOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSubjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSubjectBadRequestCode is the HTTP code returned for type UpdateSubjectBadRequest
const UpdateSubjectBadRequestCode int = 400

/*
UpdateSubjectBadRequest Bad Request

swagger:response updateSubjectBadRequest
*/
type UpdateSubjectBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewUpdateSubjectBadRequest creates UpdateSubjectBadRequest with default headers values
func NewUpdateSubjectBadRequest() *UpdateSubjectBadRequest {

	return &UpdateSubjectBadRequest{}
}

// WithPayload adds the payload to the update subject bad request response
func (o *UpdateSubjectBadRequest) WithPayload(payload *models.ErrorOut) *UpdateSubjectBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update subject bad request response
func (o *UpdateSubjectBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSubjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSubjectNotFoundCode is the HTTP code returned for type UpdateSubjectNotFound
const UpdateSubjectNotFoundCode int = 404

/*
UpdateSubjectNotFound Not Found

swagger:response updateSubjectNotFound
*/
type UpdateSubjectNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewUpdateSubjectNotFound creates UpdateSubjectNotFound with default headers values
func NewUpdateSubjectNotFound() *UpdateSubjectNotFound {

	return &UpdateSubjectNotFound{}
}

// WithPayload adds the payload to the update subject not found response
func (o *UpdateSubjectNotFound) WithPayload(payload *models.ErrorOut) *UpdateSubjectNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update subject not found response
func (o *UpdateSubjectNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSubjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSubjectInternalServerErrorCode is the HTTP code returned for type UpdateSubjectInternalServerError
const UpdateSubjectInternalServerErrorCode int = 500

/*
UpdateSubjectInternalServerError Internal Server Error

swagger:response updateSubjectInternalServerError
*/
type UpdateSubjectInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewUpdateSubjectInternalServerError creates UpdateSubjectInternalServerError with default headers values
func NewUpdateSubjectInternalServerError() *UpdateSubjectInternalServerError {

	return &UpdateSubjectInternalServerError{}
}

// WithPayload adds the payload to the update subject internal server error response
func (o *UpdateSubjectInternalServerError) WithPayload(payload *models.ErrorOut) *UpdateSubjectInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update subject internal server error response
func (o *UpdateSubjectInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSubjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
