// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ExternalSubjectID The external subject identifier.
//
// swagger:model external_subject_id
type ExternalSubjectID string

// Validate validates this external subject id
func (m ExternalSubjectID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 64); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this external subject id based on context it is used
func (m ExternalSubjectID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
