// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// InternalSubjectID The internal subject identifier.
//
// swagger:model internal_subject_id
type InternalSubjectID string

// Validate validates this internal subject id
func (m InternalSubjectID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 36); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 36); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this internal subject id based on context it is used
func (m InternalSubjectID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
