// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResourceTypesOut A list of resource types.
//
// swagger:model resource_types_out
type ResourceTypesOut struct {

	// The list of resource types.
	// Required: true
	ResourceTypes []*ResourceTypeOut `json:"resource_types"`
}

// Validate validates this resource types out
func (m *ResourceTypesOut) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceTypesOut) validateResourceTypes(formats strfmt.Registry) error {

	if err := validate.Required("resource_types", "body", m.ResourceTypes); err != nil {
		return err
	}

	for i := 0; i < len(m.ResourceTypes); i++ {
		if swag.IsZero(m.ResourceTypes[i]) { // not required
			continue
		}

		if m.ResourceTypes[i] != nil {
			if err := m.ResourceTypes[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resource_types" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resource_types" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this resource types out based on the context it is used
func (m *ResourceTypesOut) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResourceTypes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceTypesOut) contextValidateResourceTypes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ResourceTypes); i++ {

		if m.ResourceTypes[i] != nil {

			if swag.IsZero(m.ResourceTypes[i]) { // not required
				return nil
			}

			if err := m.ResourceTypes[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resource_types" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resource_types" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResourceTypesOut) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceTypesOut) UnmarshalBinary(b []byte) error {
	var res ResourceTypesOut
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
