// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// SubjectSourceID The subject source ID.
//
// swagger:model subject_source_id
type SubjectSourceID string

// Validate validates this subject source id
func (m SubjectSourceID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 255); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this subject source id based on context it is used
func (m SubjectSourceID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
