// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubjectIn An incoming subject.
//
// swagger:model subject_in
type SubjectIn struct {

	// subject id
	// Required: true
	SubjectID *ExternalSubjectID `json:"subject_id"`

	// subject type
	// Required: true
	SubjectType *SubjectType `json:"subject_type"`
}

// Validate validates this subject in
func (m *SubjectIn) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubjectType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubjectIn) validateSubjectID(formats strfmt.Registry) error {

	if err := validate.Required("subject_id", "body", m.SubjectID); err != nil {
		return err
	}

	if m.SubjectID != nil {
		if err := m.SubjectID.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("subject_id")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("subject_id")
			}

			return err
		}
	}

	return nil
}

func (m *SubjectIn) validateSubjectType(formats strfmt.Registry) error {

	if err := validate.Required("subject_type", "body", m.SubjectType); err != nil {
		return err
	}

	if m.SubjectType != nil {
		if err := m.SubjectType.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("subject_type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("subject_type")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this subject in based on the context it is used
func (m *SubjectIn) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSubjectID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSubjectType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubjectIn) contextValidateSubjectID(ctx context.Context, formats strfmt.Registry) error {

	if m.SubjectID != nil {

		if err := m.SubjectID.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("subject_id")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("subject_id")
			}

			return err
		}
	}

	return nil
}

func (m *SubjectIn) contextValidateSubjectType(ctx context.Context, formats strfmt.Registry) error {

	if m.SubjectType != nil {

		if err := m.SubjectType.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("subject_type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("subject_type")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubjectIn) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubjectIn) UnmarshalBinary(b []byte) error {
	var res SubjectIn
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
